config/routes.rb
Sklep::Application.routes.draw do
  localized do
    root "home#index"

    namespace :admin do
      resources :products do
        resources :product_variants, path: 'variants', as: :variants, except: "show"
      end
      resources :product_types
      root to: "home#index"
      resources :users
      resources :orders
      resources :admin_users
      devise_for :users, class_name: "AdminUser", module: :devise, path: "admin_user", controllers: {
        passwords: 'admin/passwords',
        registrations: "admin/registrations", 
        sessions: "admin/sessions"
      }
    end
  
    resources :products
  
    devise_for :users, controllers: { 
      passwords: 'users/passwords',
      registrations: "users/registrations", 
      sessions: "users/sessions", 
      omniauth_callbacks: "users/omniauth_callbacks", 
      confirmations: 'users/confirmations'
    }
  
    # Cart
  
    get "cart", to: "cart_steps#show", id: "fresh"
    resource :cart, only: [:destroy]
      scope "cart/steps" do
        CartSteps::Collection::STEPS.each do |step|
        get step, to: "cart_steps#show", id: step, as: "cart_#{step}_step"
        patch step, to: "cart_steps#update", id: step
      end
    end
  
    get "cart", to: "cart_steps#show", id: "fresh"
    resources :cart_items, only: [:create]
    resources :orders, only: [:show, :index, :update]

    get "search", to: "search#index"
    get "search/autocomplete", to: "search#autocomplete", as: "search_autocomplete"
    get "quality", to: "home#quality"
    get "term_of_use", to: "home#terms_of_use"
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :cart
  belongs_to :shipping_address
  belongs_to :billing_address, inverse_of: :order
  has_many :items, class_name: "OrderItem", dependent: :destroy
  has_one :payment, dependent: :destroy
  
  before_create :generate_auth_token
  after_create Order::Notifier
  after_save Order::Notifier
  
  mount_enumeration :shipping_method, Enumerations::ShippingMethod
  mount_enumeration :payment_method, Enumerations::PaymentMethod
  mount_enumeration :status, Enumerations::OrderStatus
  
  accepts_nested_attributes_for :shipping_address, :billing_address
  
  validates :cart_id, :auth_token, uniqueness: true
  
  def assigned?
    user.present?
  end
  
  def guest?
    !assigned?
  end
  
  def ready?
    status == "ready"
  end
  
  def sent?
    status == "sent"
  end
  
  def paid_at
    payment.success? ? payment.current_status.created_at : nil
  end
  
  def new?
    status == "new"
  end
  
  def canceled?
    status == "canceled"
  end
  
  def amount_due
    items_amount_due + shipping_price.to_f
  end
  
  def items_amount_due
    items.inject(0) { |sum, item| sum + item.amount_due }
  end
  
  def payment_status
    payment.status
  end  
     
  def update_status!(status)
    self.status = status
    save
  end
  
  private
  
  def generate_auth_token
    self.auth_token = SecureRandom.urlsafe_base64(nil, false) while auth_token.nil? || Order.where(auth_token: auth_token).exists?
  end
  
end

app/models/order/notifier.rb
class Order::Notifier
  attr_reader :record, :callback
  
  def initialize(record, callback)
    @record = record
    @callback = callback
  end
  
  def self.after_create(record)
    begin
      self.new(record, "after_create").dispatch
    rescue
    end
  end
  
  def self.after_save(record)
    begin
      self.new(record, "after_save").dispatch
    rescue
    end
  end
      
  def dispatch
    send(method_name)
  end

  private
  
  def after_save_order
    order_sent if record.sent? && record.status_changed?
    order_canceled if record.canceled? && record.status_changed?
  end
  
  def after_create_payment_status
    if record.success? 
      order_paid if record.order.new?
      new_virtualo_transaction if record.order.any_ditital_items?
    end
  end
  
  def after_create_order
    new_order
  end

  def method_name
    [callback, record.class.to_s.underscore].join("_")
  end
  
  def order_sent
    OrdersMailer.order_sent(record).deliver
  end
  
  def order_canceled
    OrdersMailer.order_canceled(record).deliver
  end
  
  def order_paid
    record.order.update_status!("ready")
    OrdersMailer.order_paid(record.order).deliver
  end
  
  def new_order
    OrdersMailer.new_order(record).deliver    
  end
    
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  
  def index
    @q = Order.ransack(params[:q])
    @orders = Order.all
    @orders = @q.result.page(params[:page]).per(30)
    
    respond_to do |format|
      format.html
      #format.xlsx { render :xlsx => "daily_reports", :filename => "zamowienia.xlsx" }
    end
  end
  
  def show
    @order = Order.find(params[:id])
    @order = OrderDecorator.decorate(@order)
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:update, :show]

  def index
    @orders = policy_scope(Order.ordered)
    @orders = @orders.filtered_by(params[:filter]) unless params[:filter].nil?
    @orders = @orders.page(params[:page]).per(25)
    
    respond_to do |format|
      format.html
      format.json { render json: @orders }
    end
  end
  
  def user_index
    @user = User.find(params[:user_id])
    @orders = policy_scope(@user.orders.ordered)
    
    authorize @user, :show?
    authorize @orders
    
    respond_to do |format|
      format.html
      format.json { render json: @orders }
    end
  end
  
  def show
    authorize @order
    @order = OrderDecorator.decorate(@order)
    @items = OrderItemDecorator.decorate_collection(@order.items)
    @payment = PaymentDecorator.decorate(@order.payment)
    respond_to do |format|
      format.html
      format.json { render json: @order }
    end
  end
  
  def update
    order_params = params.require(:order).permit(:status)
    authorize(@order)
    
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to orders_path, notice: 'Zamówienie zostało pomyślnie zaktualizowane.' }
        format.json { head :no_content }
      else
        format.html { redirect_to orders_path }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end  
    
  private
  
  def set_order
    @order = Order.find(params[:id])
  end  
  
  def decorated_payment
    PaymentDecorator.decorate(@order.payment)
    # if @order.payment.pay_u?
#       #PayUPaymentDecorator.decorate(@order.payment)
#     else
#       PaymentDecorator.decorate(@order.payment)
#     end
  end
end

app/views/admin/orders/index.html.haml
- content_for :search do
  = simple_form_for [:admin, @q], url: admin_orders_path, method: :get do |f|
    = f.input :email_or_id_eq, placeholder: "Szukaj wg ID lub email", label: false, input_html: { class: "form-control" }
    = f.input :created_at_gteq, label: false, placeholder: "Data początkowa", include_blank: true, input_html: { class: "datepicker form-control" }
    = f.input :created_at_lteq, label: false, placeholder: "Data końcowa", include_blank: true, input_html: { class: "datepicker form-control" }
    = f.button :submit, "Szukaj", class: "btn btn-primary"
    - if search_active?(@q)
      = link_to admin_users_path, class: "btn btn-mini btn-danger", title: "Wyczyść" do
        %i.icon.icon-remove

%table.table.table-striped
  %tr
    %th= sort_link(@q, :id, "ID") 
    %th= sort_link(@q, :created_at, "Data zamówienia")
    %th= sort_link(@q, :email, "Zamawiający")
    %th= sort_link(@q, :status, "Status")
    %th 
  -@orders.each do |order| 
    %tr
      %td= order.id
      %td= order.created_at
      %td= order.email
      %td= order.status
      %td
        .pull-right
          .btn-group
            = link_to admin_order_path(order), class: "btn btn-primary" do
              %i.icon-info-sign
              Szczegóły
            = link_to edit_admin_order_path(order), class: "btn btn-default" do
              %i.icon-edit
              Edytuj

app/views/admin/orders/show.html.haml
%h1= "Zmówienie nr #{@order.id}"

- unless @order.comment.nil?
  %dt Komentarz do zamówienia:
  %dd= @order.comment

%h2 Dane do wysyłki:
%dl
  %dt Imię i nazwisko
  %dd= @order.user_name
  %dt Adres:
  %dd= @order.address
  %dt Numer telefonu:
  %dd= @order.phone_number
  
%h2 Dane do faktury:
- if @order.invoice.present?
  - if @order.custom_billing_address.present?
    %p Dane takie jak przy wysyłce
  - else
  %dl
    %dt Nazwa firmy:
    %dd= @order.billing_address.company_name
    %dt NIP
    %dd= @order.billing_address.company_nip
    %dt Adres:
    - if @order.custom_billing_address == false
      %dd Adres jak przy wysyłce
    - else
      %dd 
        = @order.billing_address.street_and_number
        = @order.billing_address.postal_code
        = @order.billing_address.city
- else
  %p Użytkownik nie potrzebuje faktury
  
%h2 Płatność i dostawa
%dl
  %dt Płatność:
  %dd= @order.payment_method
  %dt Dostawa:
  %dd= @order.shipping_method