config/routes.rb
Sklep::Application.routes.draw do
  localized do
    root "home#index"

    namespace :admin do
      resources :products do
        resources :product_variants, path: 'variants', as: :variants, except: "show"
      end
      resources :product_types
      root to: "home#index"
      resources :users
      resources :orders
      resources :admin_users
      devise_for :users, class_name: "AdminUser", module: :devise, path: "admin_user", controllers: {
        passwords: 'admin/passwords',
        registrations: "admin/registrations", 
        sessions: "admin/sessions"
      }
    end
  
    resources :products
  
    devise_for :users, controllers: { 
      passwords: 'users/passwords',
      registrations: "users/registrations", 
      sessions: "users/sessions", 
      omniauth_callbacks: "users/omniauth_callbacks", 
      confirmations: 'users/confirmations'
    }
  
    # Cart
  
    get "cart", to: "cart_steps#show", id: "fresh"
    resource :cart, only: [:destroy]
      scope "cart/steps" do
        CartSteps::Collection::STEPS.each do |step|
        get step, to: "cart_steps#show", id: step, as: "cart_#{step}_step"
        patch step, to: "cart_steps#update", id: step
      end
    end
  
    get "cart", to: "cart_steps#show", id: "fresh"
    resources :cart_items, only: [:create]
    resources :orders, only: [:show, :index, :update]

    get "search", to: "search#index"
    get "search/autocomplete", to: "search#autocomplete", as: "search_autocomplete"
    get "quality", to: "home#quality"
    get "term_of_use", to: "home#terms_of_use"
  end
  
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
   
  def index
  end
  
  private
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @products = Product.all
  end
  
  def quality
  end
  
  def terms_of_use
  end
  
end

app/views/home/index.html.haml
.carousel-wrapper
  %ul.carousel{ data: { role: "carousel" } }
    - @products.with_bargain.each do |product|
      %li{ data: { role: "item" } }
        .nav-icon.prev.small-icon{ data: { role: "nav-link" } }
        .nav-icon.next.small-icon{ data: { role: "nav-link" } }
        .description
          .title= product.name
          .content= product.description
          .fabric
            Skład: 
            = product.fabric
          = link_to "zobacz", product_path(product.id), class: "more"
        .photo
          = image_tag product.picture.full_view, alt: "sypialnia"    
.categories-wrapper
  %h1 Najchętniej kupowane:
  %ul
    - @products.bestsellers.take(4).each do |product|
      %li
        = link_to product_path(product) do
          .photo= image_tag product.picture.full_view_thumb
          %h2= product.name
  .clearfix
      
%ul.advantages
  %li.advantage
    .advantage-icons.free-shipping
    .description Przy zamówieniach powyżej 200zł dostawa gratis!
    = link_to "więcej", "", class: "more"
  %li.advantage
    .advantage-icons.good-quality
    .description Gwarancja najwyższej jakości polskich materiałów.
    = link_to "więcej", quality_path, class: "more"
  %li.advantage
    .advantage-icons.gifts
    .description Na życzenie Klienta towar pakujemy jako prezent.
    = link_to "więcej", "", class: "more"
  %li.advantage.bargains
    .advantage-icons.bargains
    .description Korzystna oferta cenowa.
    =# link_to "więcej", bargain_path, class: "more"
.clearfix

app/views/home/quality.html.haml
%section.fabric-quality
  .left-column
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  .right-column
    = image_tag "quality-background.jpg"
  .clearfix