config/routes.rb
Sklep::Application.routes.draw do
  localized do
    root "home#index"

    namespace :admin do
      resources :products do
        resources :product_variants, path: 'variants', as: :variants, except: "show"
      end
      resources :product_types
      root to: "home#index"
      resources :users
      resources :orders
      resources :admin_users
      devise_for :users, class_name: "AdminUser", module: :devise, path: "admin_user", controllers: {
        passwords: 'admin/passwords',
        registrations: "admin/registrations", 
        sessions: "admin/sessions"
      }
    end
  
    resources :products
  
    devise_for :users, controllers: { 
      passwords: 'users/passwords',
      registrations: "users/registrations", 
      sessions: "users/sessions", 
      omniauth_callbacks: "users/omniauth_callbacks", 
      confirmations: 'users/confirmations'
    }
  
    # Cart
  
    get "cart", to: "cart_steps#show", id: "fresh"
    resource :cart, only: [:destroy]
      scope "cart/steps" do
        CartSteps::Collection::STEPS.each do |step|
        get step, to: "cart_steps#show", id: step, as: "cart_#{step}_step"
        patch step, to: "cart_steps#update", id: step
      end
    end
  
    get "cart", to: "cart_steps#show", id: "fresh"
    resources :cart_items, only: [:create]
    resources :orders, only: [:show, :index, :update]

    get "search", to: "search#index"
    get "search/autocomplete", to: "search#autocomplete", as: "search_autocomplete"
    get "quality", to: "home#quality"
    get "term_of_use", to: "home#terms_of_use"
  end
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  has_many :variants, class_name: "ProductVariant", dependent: :destroy
  belongs_to :type, class_name: "ProductType"
  has_one :picture
  
  scope :with_bargain, -> { where("bargain = ?", true) }
  scope :bestsellers, -> { where("bestseller = ?", true) }
  
  accepts_nested_attributes_for :picture
  accepts_nested_attributes_for :variants, allow_destroy: true
  
  def colors
    %w(różowy niebieski biały szary zielony fioletowy żółty czerwony czarny brązowy)
  end
  
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  has_many :products
  
  validates :kind, uniqueness: true, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @q = Product.ransack(params[:q])
    @products = Product.all
    @products = @q.result.page(params[:page]).per(30)
    @products = PaginatingDecorator.decorate(@products, with: Admin::ProductDecorator)
    
    respond_to do |format|
      format.html
    end
    
  end
  
  def show
  end
  
  def new
    @product = Product.new
    @product.picture = Picture.new
  end
  
  def create
    @product = Product.new(product_params)
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: 'Pościel została dodana.' }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def edit
  end
  
  def update
    @product.update_attributes(product_params)
    
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to admin_product_path(@product), notice: 'Pościel została wyedytowana.' }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def destroy
    @product.destroy
    
    respond_to do |format|
      format.html { redirect_to admin_products_url }
    end
  end
  
  private
  
  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end
  
  def product_params 
    params.require(:product).permit(:name, :product_type, :amount, :fabric, :manufacturer, :description, :bargain, :bestseller,
      color: [],
      picture_attributes: [:full_view, :zoom, :pattern, :full_view_thumb, :zoom_thumb, :pattern_thumb, :id]
      )    
  end
  
end

app/controllers/products/bedclothes_controller.rb
class Products::BedclothesController < ApplicationController
  
  def index
    @bedclothes = Product.bedclothes
  end
  
end

app/controllers/products/sheets_controller.rb
class Products::SheetsController < ApplicationController
  
  def index
    @sheets = Product.sheet
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @product_search = ProductSearch.new(product_search_params)
    @products = PaginatingDecorator.decorate(@product_search.resolve, with: Product::IndexDecorator)
    respond_to(:html)
  end
  
  def show
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end
  
  def bargain
    @products = Product.with_bargain
  end
  
  private
  
  def product_search_params
    params.permit(:variant_size, :q)
  end
  
end

app/views/admin/products/_form.html.haml
= simple_form_for [:admin, @product], class: "form-horizontal" do |f|
  .form-group
  = f.simple_fields_for :picture, @product.picture do |fd|
    = fd.input :full_view, as: :file, inline_label: 'Pełne zdjęcie'
    = image_tag(@product.picture.full_view_url) if @product.picture.full_view?
    = fd.input :zoom, as: :file, inline_label: 'Zbliżenie'
    = fd.input :pattern, as: :file, inline_label: 'Wzór'
    = fd.input :full_view_thumb, as: :file, inline_label: 'Pełne zdjęcie - miniatura'
    = fd.input :zoom_thumb, as: :file, inline_label: 'Zbliżenie - miniatura'
    = fd.input :pattern_thumb, as: :file, inline_label: 'Wzór - miniatura'
  = f.input :name, input_html: { class: "form-control" }
  = f.input :description, input_html: { class: "form-control" }
  = f.input :bargain, inline_label: 'Promocja'
  = f.input :amount, input_html: { class: "form-control" }
  = f.input :type_id, collection: ProductType.all, value_method: :id, label_method: :kind, input_html: { class: "form-control" }
  = f.input :manufacturer, input_html: { class: "form-control" }
  = f.input :fabric, input_html: { class: "form-control" }
  = f.input :color, name: "Wybierz pasujący kolor", collection: @product.colors, input_html: { class: "form-control chosen-input", multiple: "true", data: { placeholder: "Wybierz pasujący kolor"} }
  = f.input :bestseller, inline_label: 'Bestseller'
  .actions
    = f.button :submit, class: "btn btn-primary"

app/views/admin/products/index.html.haml
- content_for :search do
  = simple_form_for [:admin, @q], url: admin_products_path, method: :get do |f|
    = f.input :id_eq, placeholder: "Szukaj wg ID lub nazwy", label: false

- content_for :actions do
  = link_to new_admin_product_path, class: "btn btn-default" do
    %i.icon-plus-sign
    Dodaj pościel

%table.table.table-striped
  %tr
    %th= sort_link(@q, :id, "ID") 
    %th= sort_link(@q, :name, "Nazwa")
    %th Rozmiar (cena)
    %th Cena
    %th= sort_link(@q, :amount, "Ilość")
    %th Zdjęcie
    %th 
  -@products.each do |product| 
    %tr
      %td= product.id
      %td= product.name
      %td
        - product.variants.each do |variant|
          = "#{variant.size} (#{format_price(variant.price)})"
          %br
      %td= product.amount
      %td= image_tag product.picture.full_view_thumb
      %td
        .pull-right
          .btn-group
            = link_to admin_product_path(product), class: "btn btn-primary" do
              %i.icon-info-sign
              Pokaż
            = link_to edit_admin_product_path(product), class: "btn btn-default" do
              %i.icon-edit
              Edytuj
            = link_to admin_product_path(product), method: :delete, confirm: "Czy na pewno chcesz usunąć produkt \"#{product.name}\"?", class: "btn btn-danger" do
              %i.icon-trash 
              Usuń
            = link_to admin_product_variants_path(product), class: "btn btn-default" do
              %i.icon-info-sign
              Pokaż warianty
              

app/views/admin/products/show.html.haml
- content_for :actions do
  .btn-group
    = link_to "Edytuj", edit_admin_product_path(@product), icon: :edit, class: "btn btn-primary"
    = link_to "Usuń", admin_product_path(@product), method: :delete, class: "btn btn-danger",
      confirm: "Czy na pewno chcesz usunąć produkt \"#{@product.name}\"?", icon: :trash

%dl
  %dt Id: 
  %dd= @product.id
  %dt Nazwa:
  %dd= @product.name