config/routes.rb
Sklep::Application.routes.draw do
  localized do
    root "home#index"

    namespace :admin do
      resources :products do
        resources :product_variants, path: 'variants', as: :variants, except: "show"
      end
      resources :product_types
      root to: "home#index"
      resources :users
      resources :orders
      resources :admin_users
      devise_for :users, class_name: "AdminUser", module: :devise, path: "admin_user", controllers: {
        passwords: 'admin/passwords',
        registrations: "admin/registrations", 
        sessions: "admin/sessions"
      }
    end
  
    resources :products
  
    devise_for :users, controllers: { 
      passwords: 'users/passwords',
      registrations: "users/registrations", 
      sessions: "users/sessions", 
      omniauth_callbacks: "users/omniauth_callbacks", 
      confirmations: 'users/confirmations'
    }
  
    # Cart
  
    get "cart", to: "cart_steps#show", id: "fresh"
    resource :cart, only: [:destroy]
      scope "cart/steps" do
        CartSteps::Collection::STEPS.each do |step|
        get step, to: "cart_steps#show", id: step, as: "cart_#{step}_step"
        patch step, to: "cart_steps#update", id: step
      end
    end
  
    get "cart", to: "cart_steps#show", id: "fresh"
    resources :cart_items, only: [:create]
    resources :orders, only: [:show, :index, :update]

    get "search", to: "search#index"
    get "search/autocomplete", to: "search#autocomplete", as: "search_autocomplete"
    get "quality", to: "home#quality"
    get "term_of_use", to: "home#terms_of_use"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, omniauth_providers: [:facebook]
         
         
  has_one :cart, -> { where(locked_at: nil) }
  has_many :orders
  has_many :shipping_addresses
  has_many :billing_addresses
  belongs_to :shipping_address
  belongs_to :billing_address
  
  accepts_nested_attributes_for :shipping_address
  
  
  def shipping_address
    super || build_shipping_address(first_name: first_name, last_name: last_name)
  end
  
  def self.find_for_facebook_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.skip_confirmation!
    end
  end
  
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  
  def index
    @q = User.ransack(params[:q])
    @users = User.all
    @users = @q.result.page(params[:page]).per(30)
  end
  
  def show
    @user = User.find(params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    @user = Services::OauthUserService.new(request.env["omniauth.auth"]).user
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      @user.save
      sign_in @user
      redirect_to new_user_registration_path
    end
  end
  
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  skip_before_filter :require_no_authentication
  before_filter :store_return_location  
  layout :layout_based_on_request, only: [:new]
  
  
  private
  
  def layout_based_on_request
    request.xhr? ? false : "application"
  end
  
  protected

  def store_return_location
    optional_store_location(params[:return_url])
  end
  
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  before_filter :store_return_location  
  layout :layout_based_on_request, only: [:new]
  
  
  private
  
  def layout_based_on_request
    request.xhr? ? false : "application"
  end
  
  protected

  def store_return_location
    optional_store_location(params[:return_url])
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  skip_before_filter :require_no_authentication, :only => [ :new, :create ]
  before_filter :store_return_location  
  layout :layout_based_on_request, only: [:new]
  
  
  private
  
  def layout_based_on_request
    request.xhr? ? false : "application"
  end
  
  protected

  def store_return_location
    optional_store_location(params[:return_url])
  end
  
end

app/views/admin/users/index.html.haml
- content_for :search do
  = simple_form_for [:admin, @q], url: admin_users_path, method: :get, wrapper: :search do |f|
    = f.input :email_or_last_name_cont, placeholder: "Email lub nazwisko", label: false, input_html: { class: "form-control" }
    = f.button :submit, "Szukaj", class: "btn btn-primary"
    - if search_active?(@q)
      = link_to admin_users_path, class: "btn btn-mini btn-danger", title: "Wyczyść" do
        %i.icon.icon-remove

= filters do
  = simple_form_for [:admin, @q], url: admin_users_path, method: :get do |f|
    %fieldset
      %legend Użytkownik
      = f.input :email_cont, label: "Adres e-mail"
    %fieldset
      %legend Zakres dat utworzenia konta
      = f.input :created_at_gteq, as: :date, label: "Od", include_blank: true
      = f.input :created_at_lteq, as: :date, label: "Do", include_blank: true

    .form-actions.form-group
      = f.button :submit, "Filtruj", class: "btn btn-primary"
      = link_to "Wyczyść", admin_users_path, class: "btn btn-default"        

%table.table.table-striped
  %tr
    %th= sort_link(@q, :id, "ID") 
    %th= sort_link(@q, :email, "Email")
    %th= sort_link(@q, :first_name, "Imię")
    %th= sort_link(@q, :last_name, "Nazwisko")
    %th
  -@users.each do |user| 
    %tr
      %td= user.id
      %td= user.email
      %td= user.first_name
      %td= user.last_name
      %td
        .pull-right
          .btn-group
            = link_to admin_user_path(user), class: "btn btn-primary" do
              %i.icon-info-sign 
              Szczegóły
              
= paginate @users

app/views/admin/users/show.html.haml
%dl
  %dt Id: 
  %dd= @user.id
  %dt Email:
  %dd= @user.email
  %dt Imię:
  %dd= @user.first_name
  %dt Nazwisko:
  %dd= @user.last_name
  %dt Data rejestracji w serwisie:
  %dd= @user.created_at
  